version: '3.4'

services:
  _base:
    &base
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/code

  # a fully loaded development environment to test new code
  dev:
    <<: *base
